# Generated by Django 4.2 on 2024-12-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_post_tags_alter_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='replay',
            new_name='reply',
        ),
    ]
